Mobview
APJ-9/etsyjS pull request #1
Opened 2022-09-27 13:05 UTC by APJ-9

2022-09-27 15:22 UTC, donjude-eng requested changes

2022-09-27 15:22 UTC, donjude-eng commented on learned-things/creating-new-elements.js
> +function addElement(){
write the function in ES6 format.

**const x = (x, y) => { return x * y };**

2022-09-27 15:22 UTC, donjude-eng commented on learned-things/media&js.js
> +        document.body.style.backgroundColor = 'red'
rename this file to media.js or index.js

2022-09-27 15:22 UTC, donjude-eng commented on learned-things/media&js.js
> +window.addEventListener('resize',mediaFun)
are you using this listener?

2022-09-27 15:22 UTC, donjude-eng commented on learned-things/testing.js
> +signIn.style.borderRadius = '50px'
use prettier and format all these js documents?

2022-09-27 15:22 UTC, donjude-eng commented on learned-things/testing.js
> +addElement(rightSideLogo, headerHeart)
Try to pass all the arguments as an object 

example:

function someFunc(arg) {
    alert(arg.foo);
    alert(arg.bar);
}
someFunc({foo: "This", bar: "works!"});

2022-09-27 15:22 UTC, donjude-eng commented on script.js
> +document.body.style.backgroundColor = 'white'
why this?

2022-09-27 15:22 UTC, donjude-eng commented on learned-things/testing.js
> +
@APJ-9 also attach screenshots of all the devices here.

2022-09-28 06:12 UTC, APJ-9 commented on learned-things/testing.js
> +
Okay
![Screenshot from 2022-09-28 11-41-59](https://user-images.githubusercontent.com/110293755/192701432-824dc763-6a2f-4c73-9dcd-08efae315a41.png)
![Screenshot from 2022-09-28 11-41-51](https://user-images.githubusercontent.com/110293755/192701441-e261966f-b7f8-4a26-bf0c-91dcaf5e91ee.png)

2022-09-28 06:13 UTC, APJ-9 commented on learned-things/testing.js
> +
Uploaded My Clone view and original site view

2022-09-28 12:35 UTC, APJ-9 commented
My Work
![Screenshot from 2022-09-28 18-03-21](https://user-images.githubusercontent.com/110293755/192779515-7a8e2379-aa73-437e-9ba5-146fc0e29126.png)

Original Site 
![Screenshot from 2022-09-28 18-03-15](https://user-images.githubusercontent.com/110293755/192779529-ab9bdcb1-823c-4d53-ac6b-ee56510fad9a.png)

2022-09-29 12:09 UTC, merged

2022-09-29 12:49 UTC, APJ-9 commented
Created by me:-
![Screenshot from 2022-09-29 18-15-44](https://user-images.githubusercontent.com/110293755/193034971-9fdd770c-362a-463c-ae32-0512e9f8d83f.png)

Orginal Site
![Screenshot from 2022-09-29 18-14-58](https://user-images.githubusercontent.com/110293755/193035256-8dca0d96-7830-45e9-8d53-ff464661e48d.png)